language: python
python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.5"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.2"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="django>=1.5,<1.6"
    - python: "2.6"
      env: DJANGO="django>=1.6,<1.7"
    - python: "2.6"
      env: DJANGO="django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="django>=1.8,<1.9"
install:
  - pip install $DJANGO
  - pip install nose flake8 coveralls
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'jinja2<2.7'; else pip install 'jinja2>=2.7'; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]]; then pip install 'coverage<4'; else pip install 'coverage>=4'; fi
script:
  - flake8 --show-source django_activeurl
  - python setup.py nosetests --with-coverage
after_success:
  - coveralls
