language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO=https://github.com/django/django/tarball/stable/1.5.x#egg=django
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.2"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x#egg=django
    - python: "2.5"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x#egg=django
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q lxml>=2.3.5 django-classy-tags>=0.4 nose coverage --use-mirrors
script: python setup.py nosetests --with-coverage --cover-package='django_activeurl'
