language: python

sudo: false

matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-flake8
    - python: 3.6
      env: TOXENV=py36-flake8

    - python: 2.7
      env: TOXENV=py27-isort
    - python: 3.6
      env: TOXENV=py36-isort

    - python: 2.7
      env: TOXENV=py27-dj18
    - python: 3.3
      env: TOXENV=py33-dj18
    - python: 3.4
      env: TOXENV=py34-dj18
    - python: 3.5
      env: TOXENV=py35-dj18


    - python: 2.7
      env: TOXENV=py27-dj110
    - python: 3.4
      env: TOXENV=py34-dj110
    - python: 3.5
      env: TOXENV=py35-dj110

    - python: 2.7
      env: TOXENV=py27-dj111
    - python: 3.4
      env: TOXENV=py34-dj111
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.6
      env: TOXENV=py36-dj111

    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-djmaster


  allow_failures:
    - python: 3.5
      env: TOXENV=py35-djmaster
    - python: 3.6
      env: TOXENV=py36-djmaster

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install codecov
  - codecov
