language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
env:
  - DJANGO=django==1.3.7
  - DJANGO=django==1.4.5
  - DJANGO=https://github.com/django/django/tarball/stable/1.5.x
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=django==1.3.7
    - python: "3.3"
      env: DJANGO=django==1.4.5
    - python: "3.2"
      env: DJANGO=django==1.3.7
    - python: "3.2"
      env: DJANGO=django==1.4.5
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x
    - python: "2.5"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x
install:
  - pip install -q $DJANGO --use-mirrors
  - pip install -q lxml==3.1.0 django-classy-tags==0.4 nose==1.2.1 coverage==3.6 --use-mirrors
script: python setup.py nosetests --with-coverage --cover-package='django_activeurl'
