language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
env:
  - DJANGO=django==1.3.5
  - DJANGO=django==1.4.3
  - DJANGO=https://github.com/django/django/tarball/stable/1.5.x
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO=django==1.3.5
    - python: "3.3"
      env: DJANGO=django==1.4.3
    - python: "3.2"
      env: DJANGO=django==1.3.5
    - python: "3.2"
      env: DJANGO=django==1.4.3
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x
    - python: "2.5"
      env: DJANGO=https://github.com/django/django/tarball/stable/1.5.x
install:
  - pip install $DJANGO --use-mirrors
  - pip install lxml==3.1.0 django-classy-tags==0.4 nose==1.2.1 --use-mirrors
script: python setup.py nosetests
