language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
  - "pypy"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.2"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="django>=1.5"
    - python: "2.5"
      env: DJANGO="django>=1.5"
install:
  - pip install $DJANGO
  - pip install -q coverage>=3.6 nose>=1.3.0 flake8>=2.0 Jinja2>=2.6
script:
  - python setup.py nosetests --with-coverage --cover-package=django_activeurl
  - "flake8 --show-source django_activeurl"
after_success:
  - sh -c "if [ '2.5' != $(python -c "import sys; print('%s.%s' % sys.version_info[:2])") ]; then pip install coveralls>=0.1.1&&coveralls; fi"
