language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "2.5"
  - "pypy"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.2"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="django>=1.5"
    - python: "2.5"
      env: DJANGO="django>=1.5"
install:
  - pip install $DJANGO --use-mirrors
  - pip install -q lxml>=2.3.5 django-classy-tags>=0.4 coverage --use-mirrors
script: python setup.py nosetests --with-coverage --cover-package='django_activeurl'
