sudo: false
language: python
python:
  # - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  - "pypy"
env:
  - DJANGO="django>=1.3,<1.4"
  - DJANGO="django>=1.4,<1.5"
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="https://github.com/django/django/tarball/stable/1.9.x#egg=django"
matrix:
  exclude:
    # - python: "3.5"
    #   env: DJANGO="django>=1.3,<1.4"
    # - python: "3.5"
    #   env: DJANGO="django>=1.4,<1.5"
    - python: "3.4"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.4"
      env: DJANGO="django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="django>=1.3,<1.4"
    - python: "3.3"
      env: DJANGO="django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="django>=1.5,<1.6"
    - python: "2.6"
      env: DJANGO="django>=1.6,<1.7"
    - python: "2.6"
      env: DJANGO="django>=1.7,<1.8"
    - python: "2.6"
      env: DJANGO="django>=1.8,<1.9"
    - python: "2.6"
      env: DJANGO="https://github.com/django/django/tarball/stable/1.9.x#egg=django"
install:
  - pip install -U pip
  - travis_retry pip install $DJANGO
  - travis_retry pip install lxml django-classy-tags django_appconf jinja2
  - travis_retry pip install nose coverage flake8 frosted isort coveralls
script:
  - python setup.py nosetests --with-coverage
after_success:
  - flake8 --show-source django_activeurl
  - frosted -r django_activeurl
  - isort --check-only -rc django_activeurl --dif
  - coveralls
